
Dotpulse:
  Basic:
    context: Production
    HeadComment: 'Created with ♥ and passion by dotpulse.ch'
    GoogleTagManager: null
    GoogleAnalytics: null
    GoogleAnalyticsSendPageview: true
    GoogleSiteVerification: null
    GoogleFonts: null
    Polyfill: null
    Favicon: null
    ThemeColor: null
    SafariPinColor: null
    Name: null
    VersionOfAssets: null
    LoadCSSAsynchron: false
    replaceWithShy: false
    basicRegex: '(?=[^<]*+(?:<(?!\/?(?:textarea|pre|script)\b)[^<]*+)*+(?:<(?>textarea|pre|script)\b|\z))'
    General:
      Head:
        Style: null
        Script: null
      Body:
        Style: null
        Script: null
    Backend:
      Head:
        Style: null
        Script: null
      Body:
        Style: null
        Script: null
    Live:
      Head:
        Style: null
        Script: null
      Body:
        Style: null
        Script: null
    AssetTranslation:
      BySeparator: null
Neos:
  Flow:
    i18n:
      defaultLocale: de
  Neos:
    userInterface:
      defaultLanguage: de
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          loadingDepth: 2
      translation:
        autoInclude:
          Dotpulse.Basic:
            - '*'
    fusion:
      autoInclude:
        Dotpulse.Basic: true
  Fusion:
    defaultContext:
      Dotpulse.Basic.AssetTranslation: Dotpulse\Basic\Eel\Helper\AssetTranslationHelper
