TYPO3:
  Flow:
    i18n:
      defaultLocale: de
  Neos:
    # transliterationRules:
    #   'de':
    #     '||': ''
    #     '---': ''
    userInterface:
      defaultLanguage: de
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          loadingDepth: 2
      translation:
        autoInclude:
          'Dotpulse.Basic': ['*']
    typoScript:
      autoInclude:
        'Dotpulse.Basic': true
  TypoScript:
    defaultContext:
      # usage: Dotpulse.Basic.AssetTranslation.translate('de text | fr text | it text')
      # @see www/Neos/Packages/Plugins/Dotpulse.Basic/Classes/Dotpulse/Base/Eel/Helper/AssetTranslationHelper.php
      'Dotpulse.Basic.AssetTranslation': 'Dotpulse\Basic\Eel\Helper\AssetTranslationHelper'

# Filenames are comma separated
#  * intern: Just the name e.g. "Main"
#  * extern: e.g. //ajax.googleapis.com/...
#  * If you want to add attributes, add it with square brackets e.g. Filename[async data-prop data-attr="true"]

Dotpulse:
  Basic:
    context: Production
    HeadComment: 'Created with ♥ and passion by dotpulse.ch'
    GoogleTagManager: # Incl. GTM-
    GoogleAnalytics:
    GoogleAnalyticsSendPageview: true
    GoogleSiteVerification:
    GoogleFonts:
    Polyfill: #use of polyfill.io. if true, all get's included. With a string, a ?features=STRING will be added
    Favicon:
    ThemeColor:
    SafariPinColor:
    Name:
    VersionOfAssets: #add a value to prevent caching issues
    LoadCSSAsynchron: false
    replaceWithShy: false # Which string should be replaced with &shy; Please use regex style. For e.g. "||" write "\|\|"
    basicRegex: '(?=[^<]*+(?:<(?!\/?(?:textarea|pre|script)\b)[^<]*+)*+(?:<(?>textarea|pre|script)\b|\z))' # Basic Regex for safe replacement
    #Filenames
    General:
      Head:
        Style:
        Script:
      Body:
        Style:
        Script:
    Backend:
      Head:
        Style:
        Script:
      Body:
        Style:
        Script:
    Live:
      Head:
        Style:
        Script:
      Body:
        Style:
        Script:
    AssetTranslation:
      BySeparator: ~ # could be: '|'
