
Dotpulse:
  Basic:
    context: Development
    GoogleTagManager: false
    GoogleAnalytics: false
    GoogleSiteVerification: false
    Favicon: false
Neos:
  Flow:
    security:
      session:
        inactivityTimeout: 0
