TYPO3:
  Flow:
    security:
      session:
        inactivityTimeout: 0

Dotpulse:
  Basic:
    context: Development
    GoogleTagManager: false
    GoogleAnalytics: false
    GoogleSiteVerification : false
    Favicon: false
